services:
  - type: web
    name: pythonbd-web
    runtime: python
    buildCommand: pip install -r requeriments.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pythonbd-db
          property: connectionString

databases:
  - name: pythonbd-db
    plan: free