services:
  - type: web
    name: pythonbd-web
    runtime: python
    rootDirectory: pythonBD/  # ¡Nuevo! Especifica la carpeta donde está tu código
    buildCommand: |
      pip install -r requirements.txt &&
      pip install gunicorn
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pythonbd-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.11  # Versión específica

databases:
  - name: pythonbd-db
    plan: free
    region: oregon  # Asegúrate que coincida con tu región