services:
  - type: web
    name: pythonbd-web
    runtime: python
    rootDirectory: pythonBD/
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn app:app --bind=0.0.0.0:10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pythonbd-db
          property: connectionString

databases:
  - name: pythonbd-db
    plan: free